version: "3.7"

services:

  db-test:
    container_name: 'homepage-db-test'
    image: 'postgres:11.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'

  db-dev:
    container_name: 'homepage-db-dev'
    image: 'postgres:11.2'
    ports:
      - '25432:5432'
    environment:
      - 'POSTGRES_USER=dev'
      - 'POSTGRES_DB=dev'
      - 'POSTGRES_PASSWORD=dev'

  db-prod:
    container_name: 'homepage-db-prod'
    image: 'postgres:11.2'
    ports:
      - '35432:5432'
    environment:
      - 'POSTGRES_USER=prod'
      - 'POSTGRES_DB=prod'
      - 'POSTGRES_PASSWORD=prod'