version: '3'

services:
  homepage-api:
    container_name: 'homepage-api'
    build: .
    tty: true
    volumes:
      - ..:/workspace
      - .bashrc:/root/.bashrc
      - $HOME/.ssh:/root/.ssh
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - '28000:8001'
    depends_on:
      homepage-db:
        condition: service_healthy
      homepage-db-test:
        condition: service_healthy
    command: bash -c "
                diesel setup --database-url postgres://main:main@homepage-db/homepage 
             && diesel setup --database-url postgres://test:test@homepage-db-test/homepage 
             && tail -f /dev/null "
           
      
  homepage-db:
    container_name: 'homepage-db'
    image: 'postgres:11.2'
    ports:
      - '15432:5432'
    user: ${POSTGRES_USER}
    environment:
      - 'POSTGRES_USER=main'
      - 'POSTGRES_DB=homepage'
      - 'POSTGRES_PASSWORD=main'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 1s

  homepage-db-test:
    container_name: 'homepage-db-test'
    image: 'postgres:11.2'
    ports:
      - '25432:5432'
    user: ${POSTGRES_USER}
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=homepage'
      - 'POSTGRES_PASSWORD=test'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s

  nginx:
    container_name: 'nginx-rust'
    image: 'nginx:latest'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - 'homepage-api'
    volumes:
      - '../nginx.conf:/etc/nginx/nginx.conf'
      - '/Users/john/certs/cert.pem:/etc/nginx/conf.d/ssl/cert.pem'
      - '/Users/john/certs/key.pem:/etc/nginx/conf.d/ssl/key.pem'
