version: '0.0.1'

services:
  main:
    build: .
    tty: true
    volumes:
      - ..:/workspace
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - '28000:8001'
      
  db-test:
    container_name: 'homepage-db-test'
    image: 'postgres:11.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'

  db-dev:
    container_name: 'homepage-db-dev'
    image: 'postgres:11.2'
    ports:
      - '25432:5432'
    environment:
      - 'POSTGRES_USER=dev'
      - 'POSTGRES_DB=dev'
      - 'POSTGRES_PASSWORD=dev'