version: '0.0.1'

services:
  homepage-api:
    container_name: 'homepage-api'
    build: .
    tty: true
    volumes:
      - ..:/workspace
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - '28000:8001'
    depends_on:
      homepage-db-main:
        condition: service_healthy
      homepage-db-test:
        condition: service_healthy
    command: "  diesel setup --database-url postgres://main:main@homepage-db-main/homepage 
             && diesel setup --database-url postgres://test:test@homepage-db-test/homepage"
           
      
  homepage-db-main:
    container_name: 'homepage-db-main'
    image: 'postgres:11.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=main'
      - 'POSTGRES_DB=main'
      - 'POSTGRES_PASSWORD=main'
    healthcheck:
      test: exit 0  
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s

  homepage-db-test:
    container_name: 'homepage-db-test'
    image: 'postgres:11.2'
    ports:
      - '25432:5432'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'
    healthcheck:
      test: exit 0  
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s