name: Hompage-api

on:
  pull_request:
    types: [opened, edited]
    branches: [ "master", "release" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      # run: docker-compose run
      # run: docker exec homepage-api
      # run: diesel-cli

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

# on:
#   merge:
#     branches: [ "master" ]

    # -----------------------
    # Docker
    # -----------------------
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Login to GitHub Container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
        
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     context: .
    #     file: ./deploy/Dockerfile
    #     tags: ${{ env.REGISTRY }}/${{ github.actor }}/homepage/api:latest

  # deploy:
  #   meeds: build
  #   runs-on: ubuntu-latest

  #   steps:
        # name: Send docker-compose.yml to a server.
            #todo: Rename docker-compose.yml of remote.
            #todo: Copy docker-compose.yml of git hub.

        # name: Log in to a server.

        # name: Exec docker-compose.yml
            #tood: docer compose down 
            #tood: docer compose up
            #todo: logout

        # test: Get response from api
            # todo: store response code

        # name: Log in to a server.
            #todo: if get 200
                # delete copied docker-comose.yml
            #todo: if get other code
                # docker compose down
                # delete copied docker-comose.yml
                # Rename renamed docker-comose.yml
                # Rename renamed docker-comose.yml
                # docker compose up
            #todo: logout