name: ci

on:
  pull_request:
    types: [ synchronize ]
    branches: [ "master", "release" ]

env:
  REGISTRY: ghcr.io
  CARGO_TERM_COLOR: always
  DOCKER_COMPOSE_YML: deploy/docker-compose.yml
  CONTAINER_NAME: homepage-api
  PATH_TO_IMAGE_CACHE:     /tmp/.buildx-cache
  PATH_TO_IMAGE_CACHE_NEW: /tmp/.buildx-cache-new

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # -----------------------
    # Docker
    # -----------------------
    - name: Login to GitHub Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ${{ env.PATH_TO_IMAGE_CACHE }}
        key: docker-${{ github.sha }}
        restore-keys: docker-

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: deploy/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        cache-from: type=local,src=${{ env.PATH_TO_IMAGE_CACHE }}
        cache-to: type=local,dest=${{ env.PATH_TO_IMAGE_CACHE_NEW}}

    - name: docker compose up
      run: |
        mkdir -p /tmp/.composer-cache
        docker compose -f ${{ env.DOCKER_COMPOSE_YML }} build
        docker compose -f ${{ env.DOCKER_COMPOSE_YML }} up -d

    - name: Move cache 
      run: |
        rm -rf ${{ env.PATH_TO_IMAGE_CACHE }}
        mv ${{ env.PATH_TO_IMAGE_CACHE_NEW}} ${{ env.PATH_TO_IMAGE_CACHE }}

    # -----------------------
    # Rust
    # -----------------------
    - name: Create an env file
      run: |
        touch .env

        echo DATABASE_URL       = ${{ secrets.DATABASE_URL }}       >> .env
        echo DATABASE_URL_TEST  = ${{ secrets.DATABASE_URL }}       >> .env

        echo ALLOWED_ORIGIN_1   = ${{ secrets.ALLOWED_ORIGIN_1 }}   >> .env
        echo ALLOWED_ORIGIN_2   = ${{ secrets.ALLOWED_ORIGIN_2 }}   >> .env

        echo LOCAL_FILE_STORAGE = ${{ secrets.LOCAL_FILE_STORAGE }} >> .env

        echo AWS_REGION         = ${{ secrets.AWS_REGIONE }}        >> .env

        echo AWS_BUCKET_TEST    = ${{ secrets.AWS_BUCKET_TEST }}    >> .env
        echo AWS_BUCKET_DEV     = ${{ secrets.AWS_BUCKET_DEV }}     >> .env
        echo AWS_BUCKET         = ${{ secrets.AWS_BUCKET }}         >> .env

        echo AWS_KEY_ID         = ${{ secrets.AWS_KEY_ID }}         >> .env
        echo AWS_KEY_SECRET     = ${{ secrets.AWS_KEY_SECRET }}     >> .env

        echo FILE_STORAGE_LOCATION = ${{ secrets.FILE_STORAGE_LOCATION }} >> .env

        cat .env

    - name: Install Python
      uses: actions/setup-python@v2

    - name: Restore mtime
      run: python ./git-restore-mtime.py

    - name: Cache Rust
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Setup Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Build Rust
      run: cargo build --verbose

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
    - name: UT
      run: | 
        docker-compose exec -T ${{ env.CONTAINER_NAME }} bash -c "cargo test --verbose"
        docker logs ${{ env.CONTAINER_NAME }}

        
